# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MM
email: website@christopherchubb.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#twitter_username: username
#github_username: chubbc
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "First Lastname"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  
#  links:
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://christopherchubb.com"
#    - label: "Email"
#      icon: "far fa-envelope"
#      url: "mailto:website@christopherchubb.com"
#    - label: "Twitter (professional)"
#      icon: "fab fa-twitter"
#      url: "https://twitter.com/QuantumChubb"
#    - label: "Twitter (personal)"
#      icon: "fab fa-twitter"
#      url: "https://twitter.com/ClassicalChubb"	
#    - label: "Google Scholar"
#      icon: "fas fa-graduation-cap"
#      url: "https://scholar.google.com.au/citations?user=s0tFhnwAAAAJ"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/chubbc"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"
  location: "University of Sydney"
  uri    : "https://www.christopherchubb.com" 
  email  : "website@christopherchubb.com"
  
  twitter_prof: "QuantumChubb"
  arxiv: "chubb_c_1"
  sciate: "cchubb"
  google_scholar: "s0tFhnwAAAAJ"  
  orcid: "0000-0002-2668-1567"
  github: "chubbc"
  
  twitter_pers: "ClassicalChubb"
  facebook: "cchubb1"
#  instagram: "cchu4043"
  steam: "chubbc"
  
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
